### PR TITLE
Add a worker test case for Andorid CVEs.

### PR DESCRIPTION
**Pull request by baekhyunwook**
This change adds a test case for Android ecosystem CVEs, which will be updated through a GCS bucket.

### CODE REVIEW

**Comment by oliverchang** [comment]
Thanks @baekhyunwook (and sorry for the delay!)

This looks great, but could you please fix the lint error here: https://github.com/google/osv/runs/5269436849?check_suite_focus=true

**Comment by baekhyunwook** [comment]
Ouch, sorry for the long delay @oliverchang; I missed your last comment.
I quickly fixed the lint error. Please take a look.

**Review by oliverchang — APPROVED** [review]
thanks!!

**Pull request merged**
