### PR TITLE
Tweak the vulnerability schema.

### PR DESCRIPTION
**Pull request by oliverchang**
This is in progress and temporarily served from /v1new.

- Hoist out some fields for affected ranges to reduce duplication.
- Generalize "cves" to "aliases".
- Add an output-only lastModified field.

### CODE REVIEW

**Review by inferno-chromium — APPROVED** [review]
Thanks for your super quick response!

**Comment by oliverchang** [comment]
FYI more changes were requested. See latest commit.

**Review by inferno-chromium — APPROVED** [review]
lgtm, 

i am even fine with just removing v1new and keeping just v1. can do later (tbr) whenever.

**Comment by oliverchang** [comment]
> lgtm,
> 
> i am even fine with just removing v1new and keeping just v1. can do later (tbr) whenever.

Need to coordinate some migration details, so holding off on that for now.

**Pull request merged**
